apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-pod
spec:
  containers:
    - name: ubuntu-sleeper-container
      image: ubuntu-sleeper
      command: ["sleep2.0"]
      args: ["10"]
# command -> override the entrypoint instruction
# arg     -> override the command instruction
