apiVersion: v1
kind: Service
metadata:
  name: ingress-service
  namespace: ingress-space
spec:
  clusterIP: 10.103.61.95
  ports:
    - name: http
      nodePort: 30080
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      nodePort: 31160
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    name: nginx-ingress
  type: NodePort
