apiVersion: v1
kind: Pod
metadata:
  name: webapp-color-pod
spec:
  containers:
    - name: webapp-color-container
      image: simple-webapp-color
      ports:
        - containerPort: 8080
      envFrom:
        - secretRef:
            name: app-secret
# secret can also be injected as environment variables
  volumes:
    - name: app-secret-volume
      secret:
        secretName: app-secret

