apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp
  labels:
    name: simple-webapp
spec:
  containers:
    - name: simple-webapp
      image: simple-webapp
      readinessProbe:
        httpGet:
          port: 8080
          path: /api/ready
        tcpSocket:
          port: 3306
        exec:
          - command:
              - cat
              - /app/is_ready
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 8
# same condition for readinessProbe and livenessProbe
      livenessProbe:
        httpGet:
          port: 8080
          path: /api/ready
        tcpSocket:
          port: 3306
        exec:
          - command:
              - cat
              - /app/is_ready
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 8
