apiVersion: v1
kind: Pod
metadata:
  name: pod-b
  namespace: ggckad-s0
spec:
  containers:
    - name: alpine-container
      image: kubegoldenguide/alpine-spin:1.0.0
    - name: nginx-container
      image: nginx:1.7.9
