apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-five-deploy
  namespace: ggckad-s5
spec:
  replicas: 6
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: revproxy
      client: user
  template:
    metadata:
      name: question-five-pod
      namespace: ggckad-s5
      labels:
        app: revproxy
        client: user
    spec:
      containers:
        - name: nginx
          image: nginx:1.7.9

