apiVersion: v1
kind: Pod
metadata:
  name: question-four-pod
  namespace: ggckad-s2
spec:
  securityContext:
    runAsGroup: 3000
  containers:
    - name: webapp-container-1
      image: kubegoldenguide/alpine-spin:1.0.0
      envFrom:
        - configMapRef:
            name: app-config
      securityContext:
        runAsUser: 1000
    - name: webapp-container-2
      image: kubegoldenguide/alpine-spin:1.0.0
      envFrom:
        - configMapRef:
            name: app-config
      securityContext:
        runAsUser: 2000
