apiVersion: v1
kind: Pod
metadata:
  name: question-two-pod
  namespace: ggckad-s2
spec:
  containers:
    - name: webapp-container
      image: kubegoldenguide/alpine-spin:1.0.0
      envFrom:
        - configMapRef:
            name: app-config
