apiVersion: v1
kind: Pod
metadata:
  name: elephant
spec:
  containers:
    - args:
        - --vm
        - "1"
        - --vm-bytes
        - 50M
        - --vm-hang
        - "1"
      command:
        - stress
      image: polinux/stress
      imagePullPolicy: Always
      name: mem-stress
      resources:
        limits:
          memory: 100Mi
        requests:
          memory: 50Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: default-token-hz9pf
          readOnly: true
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - name: default-token-hz9pf
      secret:
        defaultMode: 420
        secretName: default-token-hz9pf
