apiVersion: v1
kind: Pod
metadata:
  name: lion
spec:
  containers:
    - args:
        - -cpus
        - "3"
      image: vish/stress
      imagePullPolicy: Always
      name: cpu-stress
      resources:
        limits:
          cpu: "4"
        requests:
          cpu: "2"
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: default-token-hz9pf
          readOnly: true
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - name: default-token-hz9pf
      secret:
        defaultMode: 420
        secretName: default-token-hz9pf
