apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wp
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      name: wordpress
      app: wp
  template:
    metadata:
      labels:
        name: wordpress
        app: wp
        env: dev
    spec:
      containers:
        - name: wordpress-container
          image: wordpress
          ports:
            - containerPort: 31004
          env:
            - name : WORDPRESS_DB_HOST
              value : wordpress-mysql
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
          volumeMounts:
            - mountPath: /var/www/html
              name: wordpress-persistent-storage
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wordpress-persistent-storage

---

apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  type: NodePort
  selector:
    name: wordpress
    app: wp
  ports:
    - protocol: TCP
      port: 80
      nodePort: 31004
