apiVersion: batch/v1
kind: Job
metadata:
  name: math-add-job
spec:
  completions: 3 # the number of pods to be created
  parallelism: 3 # number of pods to be created at the same time
  template:
    spec:
      containers:
        - name: math-add
          image: ubuntu
          command: ['expr','3','+','2']
      restartPolicy: Never
