apiVersion: v1
kind: Pod
metadata:
  name: webapp-color-pod
spec:
  containers:
    - name: webapp-color-container
      image: simple-webapp-color
      ports:
        - containerPort: 8080
      envFrom:
        - configMapRef:
            name: app-config
